[[sec:secondo_lab_savoia]]
=== Realizzazione di un secondo laboratorio di informatica

Un secondo laboratorio di informatica al Savoia appare necessario e negli anni passati, con un minor numero di classi delle Scienze Applicate, veniva impiegata l'aula TEAL, ora non più disponibile. L'eventuale attivazione di altri indirizzi, tra cui il _Liceo matematico_ e il _Liceo STEAM_, potrebbe comportare la necessità di usare un laboratorio informatico anche da parte di altre materie.

Allo stato attuale si utilizza una parte del Future Lab come aula per la didattica dell'informatica con gravi difficoltà nella didattica della disciplina, come indicato nel <<sec::analisi-flab>>.

Si considera quindi una soluzione che si adegui agli spazi del Future Lab ma che sia facilmente _rilocabile_ in altre aule qualora queste divenissero disponibili.

Un secondo laboratorio potrebbe essere finanziato dal PIANO NAZIONALE DI RIPRESA E RESILIENZA, MISSIONE 4: ISTRUZIONE E RICERCA, Azione 2 su Next generation lab e nello specifico come realizzazione di laboratori per professioni digitali.
La professione digitale potrebbe essere quella della consulenza nel settore delle tecnologie informatiche e si propone progettare uno spazio dedicato alla didattica di:

* **__Sviluppo del Software__**,
* **__Intelligenza Artificiale__**,
* **__Cyber Sicurezza__**,
* **__Internet delle Cose__**,
* **__creazione di prodotti e servizi digitali__**,
* __Sistemi Operativi__,
* __Reti di Calcolatori__,
* __Physical Computing__.

Nella progettazione si considerano i vincoli individuati nel par. <<sec:requisiti-labs>>, quelli derivanti dalle caratteristiche dello spazio del Future Lab, e quello di poter facilmente rilocare gli arredi e la dotazione tecnologica in altri spazi, qualora si verificasse la loro disponibilità.

Per il secondo laboratorio di informatica del FabLab si propone di acquistare:

dotazioni digitali::
- dotazione tecnologica alternativa 1:

** almeno 30 Raspberry pi 400 8GB (6 postazioni per scrivania),
** almeno 30 monitor >= 20'' possibilmente con altoparlanti e webcam,

- dotazione tecnologica alternativa 2:

** almeno 30 Joy Pi Note (6 postazioni mobili per scrivania),

- almeno 30 micro:bit,
- almeno 30 Inventor's Kit per BBC microbit,
- almeno 30 "ribbon cable" per il collegamento dei GPIO,
- 5 switch 8 porte (uno per scrivania),
- 30 cavi patch cat. 6A 2 m.

arredi::
- 6 scrivanie.

interventi vari::
- 30 multiprese da scrivania (tre per scrivania) aventi ognuna almeno 1 presa Schuko e tre prese italiane 10+16 A,
- materiale di supporto vario tra cui: cavi di rete ed elettrici per i collegamenti delle scrivanie, canaline calpestabili per uso domestico oppure canaline in sospensione.

Per un prospetto indicativo dei costi relativi alle componenti elettroniche si veda la tab. <<tab::costiFabLab>>.

[[tab::costiFabLab]]
[options="header,footer"]
.Costi indicativi secondo laboratorio di informatica plesso Savoia
|===
|Categoria |Descrizione |Quantità |Costo unitario (IVA incl) |Costo complessivo |Link
|Dotazione tecnologica
|Raspberry Pi 4 Desktop Kit 8GB (Tastiera Italiana)
|25
|€ 199,90
|€ 4.997,50
|https://www.robotstore.it/Raspberry-Pi-4-Desktop-Kit-8GB-Tastiera-Italiana
|Dotazione tecnologica
|micro:bit V2.2 GO Kit
|25
|€ 34,90
|€ 872,50
|https://www.robotstore.it/micro-bit-V2-2-GO-Kit
|Dotazione tecnologica
|Inventor's Kit per BBC micro:bit
|25
|€ 33,80
|€ 845,00
|https://www.robotstore.it/Inventor%27s-Kit-per-BBC-micro-bit
|Dotazione tecnologica
|Lenovo ThinkVision T22v-20 - Monitor
|25
|€ 222,04
|€ 5.551,00
|https://www.campustore.it/lenovo-thinkvision-t22v-20-monitor-a-led-22-21-5.html
|Dotazione tecnologica
|D-Link GO-SW-8G - Switch
|4
|€ 26,96
|€ 107,84
|https://www.campustore.it/d-link-go-sw-8g-switch-unmanaged-8-x-10-100-1000-desktop.html
|Dotazione tecnologica
|Cavo di rete Patch in Rame Cat. 6A Grigio UTP 2 mt
|25
|€ 5,51
|€ 137,75
|https://www.campustore.it/cavo-di-rete-patch-in-rame-cat-6a-grigio-utp-2-mt.html
|Arredo
|Scrivania Practika P3
|4
|€ 339,16
|€ 1.356,64
|https://www.campustore.it/scrivania-pratika-p3-dim-180x80x73-cm.html
|Arredo
|Multipresa da scrivania bticino S3711GB
|25
|€ 33,02
|€ 825,50
|https://catalogo.bticino.it/BTI-S3711GB-IT
|Totale dotazione tecn.
|
|
|
|€ 12.511,59
|
|Totale arredo
|
|
|
|€ 2.182,14
|
|Stima piccole opere e altro materiale
|
|
|
|€ 2.000,00
|
|Totale
|
|
|
|€ 16.693,73
|
|===

=== Interventi nell'area antistante il Fab Lab

Nell'ipotesi che lo spazio antistante il Fab Lab continui ad essere impiegato come laboratorio, si di:

- installare una porta di separazione tra l'atrio dell'aula magna e la zona adibita a laboratori (eventualmente spostando il sistema di pannelli scorrevoli),
- arretrare o eliminare i pannelli scorrevoli,
- arretrare la Digital Board.