== Ipotesi architetturali

Il Dipartimento reputa interessanti alcune ipotesi da sottoporre al Team dell'Innovazione, al progettista della rete dati, al Responsabile della Protezione dei Dati e ai responsabili del Test Center ICDL.

=== Proposta n. 1 -- FUSS Server e dual boot client 

L'architettura di riferimento è quella del progetto https://it.wikipedia.org/wiki/FUSS[FUSS], meglio dettagliato nella https://fuss.bz.it/page/info/[pagina informativa].

A differenza del progetto FUSS, l'idea è quella di avere la possibilità scegliere al boot se avviare la distribuzione FUSS oppure Windows.

Nel caso di avvio con Windows, sarebbe possibile usare, nel Laboratorio di Informatica del plesso Benincasa, la rete "192.168.1.x/24" con i precedenti indirizzi per DNS e Gateway, in modo da mantenere la compatibilità piena con la situazione attuale. Il FUSS Server si limita ad inoltrare i pacchetti provenienti e destinati alla rete "192.168.1.x/24".
Se il boot avviene con FUSS Client, allora la rete è la "192.168.2.x/24", il default Gateway e il DNS puntano al FUSS Server e l'accesso alla rete avviene tramite autenticazione al portale Captive usando gli account in Active Directory.

.Architettura di rete
[plantuml, target="architettura-alto-livello", format="svg"]   
....
!include ./img/arch-net-hl.puml
....


I https://www.truelite.it/presentazioni/introduzione-architettura-fuss/[servizi] dovrebbero seguire simile al seguente schema.

.Servizi
[plantuml,targer="servizi",format="svg"]
....
title Servizi

cloud Internet {

}

package InfrastrutturaAttuale {
  component [Firewall] as FW1
  component [DNS] as DNS1
  component [LDAP]
  component [NFS]
  component [DHCP] AS DHCP1
  component [Win Domanin File Server] AS WDFS
  DNS1--FW1
  DHCP1 -- DNS1
  WDFS--LDAP
}

 
node "FUSS Server" {
    [HTTP Content Filter] AS HFW
    [HTTP Proxy cache] AS Proxy
    [SSH]
    component [DHCP] AS DHCP2
    [Veyon Master] AS VM
    [HTTP Server] AS Apache
    database "PostgreSQL" {
    }
    database "MySQL" {
    }
    
    interface IVeyon 
    
    Apache -- MySQL
    Apache -- PostgreSQL
    VM --( IVeyon
    
    Proxy -- DNS1
    Proxy -- FW1
} 


package "Windows Clients" {
    component [XMing]
    component [SSH client]
    component [MySQL Client] AS msw
    component [Browser] AS bw
    [Veyon Service] AS VCW
    VCW --( IVeyon
}

package "Linux Clients" {
    [Veyon Service] AS VCL
    VCL --( IVeyon
    [XFree86]
}


FW1 -- Internet
....


=== Transizione

Per gestire il periodo di transizione si deve tenere conto delle seguenti specifiche.

. Il sistema deve permettere la coesistenza con le tecnologie correntemente in uso
. La nuova configurazione non deve interrompere il servizio ICDL
. La rete WiFi è attualmente gestita da MasterCom con politiche di amministrazione ad hoc
. La nuova configurazione non deve interrompere il servizio di stampa
. La nuova configurazione non deve sostituire il firewall ma integrarlo

Nella fase di transizione la rete WiFi all'interno del laboratorio può restare così com'è.

=== Servizi

I FUSS Server hanno un sistema operativo Linux con Gufw come interfaccia al firewall software UFW, inoltre si possono aggiungere regole al DNS.

Il sistema permette l'accesso in `ssh` anche con il server grafico `X`. Il sistema deve configurare come suo default gateway il nodo 192.168.1.5 e come DNS il nodo 192.168.1.3.

La gestione della rete dovrebbe essere già preconfigurata ma nel caso si debbano gestire i precedenti indirizzi di rete si deve abilitare il solo IP forwarding, liberando risorse del kernel.

La RAM dovrebbe essere di almeno 16 GB, il numero di CPU pari ad almeno 8, lo spazio su disco di almeno 256 GB.

I nodi FUSS possono essere PC fisici o macchine virtuali.

Il docente deve possedere un account sui FUSS Server e deve essere nella lista dei `sudoers` (gruppo `sudo`).

Sui computer degli studenti deve essere installato FUSS Client con possibilità di __dual-boot__.
Nel caso di avvio con Windows, deve essere impostato `Veyon` per consentire il monitoraggio.

I servizi offerti dal FUSS Server sono:

* Apache HTTPD Web server
* IP stateful firewall e router 
* HTTP Proxy Cache
* HTTP Proxy Content Filter
* Proxy Secure Shell

Quelli offerti da FUSS Client sono:

* Autenticazione degli utenti tramite server LDAP
* Download e installazione dei certificati SSL necessari
* Mount delle directory HOME tramite NFS
* Installazione chiavi di autenticazione SSH
* Sincronizzazione NSCD
* Inserimento in configurazione cluster
* Creazione di utente locale di amministrazione

https://www.truelite.it/presentazioni/workshop-fuss-server/[L'installazione] ha un wizard.

Si potrebbe usare anche un solo FUSS Server creando due cluster, uno per laboratorio.

=== Pro e contro della soluzione proposta

==== Pro

* Tutte le richieste dei docenti di informatica sono soddisfatte
* Impatto sulla restante rete molto limitato

==== Contro

* Il nuovo nodo rappresenta un punto guasto aggiuntivo
* Se il nuovo nodo diventa indisponibile, la rete del laboratorio non è operativa
* la banda disponibile per PC studente si riduce notevolmente in quanto su un'unica scheda di rete ed un unico host viene gestita, via software, la connessione di tutte le postazioni del laboratorio
* il FUSS sever potrebbe essere congestionato aumentando i tempi di latenza

== Laboratori in mobilità

Una soluzione adottata da molti Istituti è quella di fornire un ambiente di calcolo, detto __classe virtuale__, che esegue il software su un server dell'Istituto ed è accessibile dai PC del laboratorio come da casa.
Di norma sono realizzate tramite tante macchine virtuali installate su un server quante sono le classi omogenee, e possono avere sistemi operativi Windows - con costi di licenza - o Unix-like - senza costi.
Nella macchina virtuale sono installati e configurati dall'assistente tecnico o dal docente  i software per la didattica.

.Uso delle _classi virtuali_
====
* L'utente accede alla propria classe mediante una porta TCP/IP ben specifica.
* Lo studente accede alle macchine virtuali con le stesse credenziali di accesso ai PC (cognome.nome e password come da sistema LDAP).

.Esempio di connessione da scuola:
* MACCHINA VIRTUALE 1ATUR : ip= 10.2.2.13
* MACCHINA VIRTUALE 5FSA: ip=10.2.2.51

.Esempio di connessione da casa:
..MACCHINA VIRTUALE 1ATUR : url= lab.iissavoiabenincasa.it porta TCP:2213
..MACCHINA VIRTUALE 5FSA: url=lab.iissavoiabenincasa.it porta TCP:2251
====

=== Pro e contro

==== Pro

* i computer del laboratorio si comportano come terminali di accesso alle macchine virtuali e necessitano di risorse minimali;
* si semplifica lo svolgimento dei compiti domestici e il loro controllo;
* si permette agli studenti di cambiare postazione nel laboratorio mantenento l'accesso ai loro dati;
* si possono controllare gli accessi di ciascun utente connesso alla macchina virtuale, anche al fine del controllo dei compiti;
////
* possibilità di proiettare lo schermo del docente su ciascun terminale connesso alla macchina virtuale della classe;
* possibilità di favorire l'uso delle macchine virtuali anche a casa, seguendo maggiormente l'andamento didattico di ciascuno studente, specialmente nello svolgimento dei compiti;
////
* si fornisce la possibilità di usare le macchine virtuali anche per l'ausilio alla docenza di altre materie. Se, ad esempio, il docente di Disegno ha bisgno di un CAD, potrebbe creare una macchina virtuale dedicata da condividere con i suoi studenti.

////
Per qeusta soluzione, già implementata in altre scuole, possiamo sentire il tecnico che ha progettato la rete di questa scuola: Matteo Bruschi.
////

==== Contro

* Spreco di risorse interne in quanto i PC del laboratorio sarebbero utilizzati come _thin client_;
* Rinnovo costi di licenza nel caso di software proprietario (Microsoft Windows (R)) sul server;
* Necessità di ingenti risorse di calcolo e di archiviazione sul server.
