= Proposte per migliorare la didattica nei Laboratori
Dipartimento di informatica - Savoia Benincasa
2022-12-22: Revisione 1.2
:figure-caption: Figura
:toc-title: Indice
:toclevels: 5
:toc: auto
:sectnums:

<<<

[quote,Renzo Davoli, ...tutto quello che avreste voluto sapere sui laboratori ma non avete mai osato chiedere...]
____
Il laboratorio:

* I Biologi hanno microscopi e vetrini
* I Chimici hanno provette e Bunsen
* I Fisici hanno acceleratori di particelle
* Noi abbiamo  **elaboratori** e **reti**
____

== Problematiche dei Laboratori

=== I Laboratori d'Informatica

L'attività didattica in laboratorio richiede un'adeguata predisposizione dei PC e dei collegamenti che non sempre si riscontra nelle attuali condizioni.

.Monitoraggio
Una problematica consiste nell'uso, da parte degli studenti, delle tecnologie per fini non didattici che l'insegnante, mentre è impegnato nella presentazione della teoria o nell'illustrazione delle tecniche e dei metodi, non riesce a rilevare. Capita, infatti, che nelle classi numerose gli studenti aprano video-giochi piuttosto che guardino pagine non inerenti l'attività didattica.

.Condivisione di videate
Un'altra problematica è la condivisione delle videate che, sebbene supportata dal proiettore, resta problematica specie per gli studenti delle ultime file.

.Stesse versioni del software
Alle volte il software richiesto per l'attività didattica risulta non disponibile in alcuni PC o installato in versioni diverse e incompatibili.

.Aggiornamento centralizzato
L'aggiornamento di un software richiede tempo in quanto ogni postazione deve essere aggiornata.

.Permanenza dei dati
In casi sporadici capita che gli studenti si autentica al PC e il sistema operativo assegna una sessione temporanea. Alla disconnessione dello studente tutti i dati vengono persi senza possibilità di ripristino.

.Controllo _fine_ della rete
Per alcune verifiche è fatto divieto di accedere a risorse esterne al proprio PC oltre a quelle del servizio di erogazione della prova e allo stato attuale il docente non ha controllo sul filtraggio di rete.
Casi rilevanti sono i _Campionati italiani e internazionali di Informatica_ e le _Olimpiadi di Informatica a Squadre_ che richiedono di disattivare l'accesso ad Internet ad eccezione della pagina della gara.

.Blocco delle pubblicità 
Per l'accesso ad alcune risorse capita che vi siano pubblicità inserite nelle pagine web e queste causano distrazione oltre a poter presentare contenuti non adatti all'ambito scolastico.

.Reti cablata e senza fili unificate
Le reti cablate e senza fili sono separate e non vi è un bridge che le renda interoperabili. Per un docente è impossibile raccogliere le prove di uno studente che opera con il suo dispositivo senza passare tramite lo scambio, insicuro, di dispositivi di storage o l'uso di piattaforme esterne.

Allo stato attuale le uniche modalità di mitigazione delle problematiche sopra esposte sono l'attenta sorveglianza da parte dell'insegnante e i tempestivi aggiornamenti del software da parte degli assistenti tecnici.

L'attuale scelta dei sistemi inoltre vincola all'utilizzo di ogni dispositivo come sistema stand-alone e solo con un sistema operativo.

Sarebbe auspicabile poter disporre di sistemi operativi aperti, con la possibilità di scegliere il sistema operativo da avviare, software e risorse di calcolo condivise.

.Accesso limitato a social network e siti di streaming
Sarebbe auspicabile filtrare l'accesso ai siti di social network e streaming consentendone solo esplicitamente l'accesso.

.Sistemi a codice sorgente aperto
Per la didattica del linguaggio C++ (classi terze ITE  SIA e Liceo Scientifico sia Scienze Applicate che opzione Inforatica), dei sistemi operativi (tutte le classi), delle reti di calcolatori (tutte le classi), delle tematiche di cybersicurezza (tutte le classi) sarebbe opportuno lavorare con Sistemi Operativi liberi quali GNU/Linux o BSD.

.Clustering
Per la sperimentazione di alcuni algoritmi particolarmente onerosi potrebbe richiedere l'utilizzo di più PC come se questi fossero un'unica potente workstation. L'architettura hardware e software deve permettere la creazione di cluster.

.Cloud privato
Per riprendere il controllo dei dati ed evitare le preoccupazioni causate dall'uso di servizi cloud gestiti da fornitori esteri, sarebbe interessante da valutare l'introduzione di una piattaforma di condivisione gestita internamente.

=== Il Future Lab

.Separazione dall'atrio dell'Aula Magna
Attualmente il Future Lab non è separato dall'ingresso dell'aula magna e questo causa distrazioni e confusione.

.Disponibilità di punti di punti luce
Attualmente la rete elettrica non dispone di punti luce tranne che sulle colonne e sulle postazioni fisse.
Andrebbero create delle strutture per ospitare delle prese elettriche funzionali all'ambiente.

.Disponibilità di punti prese di rete
Attualmente la rete dati dispone di prese ethernet solo nelle postazioni fisse.
Nelle strutture presso le quali ospitare le prese elettriche sarebbero da integrare prese per la rete cablata e/o switch.


.Disponibilità di PC/notebook
Non vi sono PC o notebook predisposti per questo ambiente e quindi si deve confidare nei dispositivi degli studenti. Si potrebbero utilizzare o i notebook dei laboratori mobili, fra cui i circa 30 presenti nel magazzino del Benincasa e non ancora utilizzati, o anche aquistare dei sistemi economici realizzati appositamente per la didattica quali le https://www.raspberrypi.com/products/raspberry-pi-400/[Rasperry Pi 400]. L'acquisto deve riguardare anche monitor con interfaccia HDMI. 

.Altre problematiche
Le altre problematiche sono le stesse dei laboratori

== Requisiti dell'ambiente laboratoriale di Informatica

Per facilitare l'insegnamento in ambienti di apprendimento digitale devono essere soddisfatte le seguenti specifiche:

. Il docente deve poter gestire i PC del laboratorio
.. Il docente deve poter monitorare a distanza i PC del laboratorio
... Il docente deve poter visualizzare la schermata dei PC del laboratorio dove sta insegnando
... Il docente deve poter salvare la schermata dei PC del laboratorio dove sta insegnando
.. Il docente deve poter controllare a distanza i PC del laboratorio
... Il docente deve poter bloccare i dispositivi di input
... Il docente deve poter prelevare da remoto i file
... Il docente deve poter trasmettere lo schermo del proprio PC a quello degli studenti
.. Il docente e studenti devono poter condividere gli schermi
. Il docente deve poter condividere applicazioni e servizi con gli studenti
.. Il docente deve poter gestire una macchina Linux, reale o virtuale, per creare e rimuovere utenti, applicazioni e servizi
.. La macchina linux si collega al servizio LDAP oppure mantiene l'elenco degli utenti
.. Il docente deve poter installare pacchetti sulla macchina Linux
.. Il docente deve poter avviare e terminare servizi sulla macchina Linux
.. I PC devono poter avviare le applicazioni sulla macchina Linux
... I PC devono supportare lo X11 forwarding per le applicazioni grafiche
. Il docente deve poter controllare gli accessi ad internet
.. Il docente deve poter impedire l'accesso ai file sul Drive e nelle cartelle condivise, ad eccezione dell'eventuale deposito della prova;
.. Il docente deve poter impedire la ricerca di informazioni nella rete Internet su siti non esplicitamente consentiti (whitelist)
.. Il docente deve poter impedire lo scambio di messaggi con sistemi di chat (es: Google Chat), webmail (es: GMail) o altro (es: Whatsapp web, Google Drive).
. Il docente deve poter controllare il DNS per rimuovere messaggi pubblicitari

=== Applicazioni

Le applicazioni che dovrebbero essere installate sono:

. Monitoraggio e controllo
.. https://veyon.io/it/[Veyon]
. Applicazioni
.. Software per l'ufficio
... https://it.libreoffice.org/[LibreOffice]
.... https://it.libreoffice.org/scopri/base/[LibreOffice Base]
.... https://it.libreoffice.org/scopri/calc/[LibreOffice Calc]
.... https://it.libreoffice.org/scopri/charts/[LibreOffice Charts]
.... https://it.libreoffice.org/scopri/draw/[LibreOffice Draw]
.... https://it.m.wikipedia.org/wiki/File:LibreOffice_6.1_Impress_Icon.svg[LibreOffice Impress]
.... https://it.libreoffice.org/scopri/math/[LibreOffice Math]
.... https://it.libreoffice.org/scopri/writer/[LibreOffice Writer]
... Software per la lettura dei PDF
.. Software per l'editoria
... https://www.tug.org/texlive/[TeX Live]
... https://www.lyx.org/[LyX]
... https://asciidoctor.org/[Asciidoctor]
.... https://docs.asciidoctor.org/diagram-extension/latest/[Asciidoctor Diagram]
.... https://docs.asciidoctor.org/pdf-converter/latest/[Asciidoctor PDF]
.... https://docs.asciidoctor.org/epub3-converter/latest/[Asciidoctor EPUB3]
.... https://docs.asciidoctor.org/reveal.js-converter/latest/[Asciidoctor reveal.js]
.... https://github.com/rouge-ruby/rouge[Ruby rouge]
.... https://github.com/rubychan/coderay[Ruby coderay]
.... https://github.com/pygments/pygments.rb[Ruby pygments.rb]
.. Stampa
... http://www.cups.org/[CUPS]
.. Interpreti, compilatori, debugger, toolchain
... https://gcc.gnu.org/[GCC, the GNU Compiler Collection]
... https://clang.llvm.org/[Clang]
... https://www.php.net/[php]
... https://nodejs.org/[Node.js] + https://pnpm.io/it/[pnpm] + https://www.typescriptlang.org/[TypeScript] + https://nativescript.org/[NativeScript]
... https://www.python.org/[Python 3]
... https://www.r-project.org/[R]
... https://www.ruby-lang.org/it/[Ruby]
... https://www.minizinc.org/[MiniZinc]
... https://www.sourceware.org/gdb/[gdb]
... https://lldb.llvm.org/[lldb]
... https://valgrind.org/[Valgrind]
... https://ghidra-sre.org/[ghidra]
... https://cmake.org/[CMake]
... https://www.gnu.org/software/make/[GNU Make]
.. Ambienti integrati di sviluppo
... https://code.visualstudio.com/[VS Code]
//... QT Creator
... https://www.codeblocks.org/[Code::Blocks IDE]
... https://www.vim.org/[vim]
... https://jupyter.org/[Jupyter Lab]
...  https://posit.co/products/open-source/rstudio/[RStudio Desktop Open Source Edition]
... http://www.flowgorithm.org/[Flowgorithm], https://www.imparando.net/sito/strumenti_di_sviluppo/flowgorithm/come_installare_in_linux.htm[sotto Linux]
... https://education.lego.com/it-it/downloads/mindstorms-ev3/software#downloads[LEGO® MINDSTORMS® Education EV3 Classroom]
... https://www.kogics.net/sf:kojo[Kojo]
... https://racket-lang.org/[Racket]
.. Strumenti di versionamento
... https://git-scm.com/[git]
.. Accesso remoto
... https://www.openssh.com/[ssh]
... https://nc110.sourceforge.io/[netcat]
... https://openvpn.net/[openVPN client]
.. Audio e video
... https://www.audacityteam.org/[Audacity]
... https://ffmpeg.org/[FFMPEG]
... https://shotcut.org/[Shotcut]
.. Browser
... https://www.mozilla.org/it-IT/firefox/[Firefox]
... https://www.google.com/intl/it_it/chrome/[Chrome]
.. CAD
... https://www.freecadweb.org/index.php?lang=it[FreeCad]
.. Grafica
... https://www.gimp.org/[GNU Image Manipulation Program]
... https://inkscape.org/[Inkscape]
... https://graphviz.org/[GraphViz]
... http://www.gnuplot.info/[GnuPlot]
... https://www.imagemagick.org/[imagemagick]
... https://plantuml.com/[PlantUML]
... https://kroki.io/[Kroki]
.. Calcolo scientifico e ingegneristico
... https://octave.sourceforge.io/[GNU Octave (octave-forge)]
... https://www.scilab.org/[Scilab]
... https://www.geogebra.org/?lang=it[GeoGebra]
... https://www.r-project.org/[R]
... https://conda.io/miniconda.html[miniconda]
.. MindMapping
... https://www.freeplane.org/[FreePlane]
... https://plantuml.com/[PlantUML]
.. Software per l'analisi della rete
... https://www.wireshark.org/[WireShark]
... https://en.wikipedia.org/wiki/Ping_(networking_utility)[ping]
... https://linux.die.net/man/8/ethtool[ethtool]
... http://www.illuminamente.org/dokuwiki/doku.php?id=educare:dnsutils[dig, dnsutils, bind-utils]
... ip
... https://it.wikipedia.org/wiki/Netcat[netcat]
... https://nmap.org/[nmap]
.. Software per la configurazione del firewall
... http://gufw.org/[gufw]
. Servizi
.. Web server
... https://httpd.apache.org/[Apache]
... https://www.nginx.com/[Nginx]
.. Data Base Management System
... https://www.postgresql.org/[PostgreSQL]
... https://www.mysql.com/[MySQL]
.. Client per SQLite
... https://sqlitebrowser.org/[DB Browser for SQLite]
... https://sqlitestudio.pl/[SQLite Studio]
... https://dbeaver.io/[DBeaver]
.. Consegna dei compiti di programmazione
... https://github.com/cms-dev/cms[CMS]
... https://github.com/algorithm-ninja/cmsocial[CMSSocial]
.. Piattaforma per il Cloud
... https://nextcloud.com/[Nextcloud]
.. Tutela della Privacy
... https://gnupg.org/[GNU GPG]
... https://apps.kde.org/it/kleopatra[Kleopatra]

== Architettura ipotizzata

L'archittura di riferimento è quella del progetto https://it.wikipedia.org/wiki/FUSS[FUSS], meglio dettagliato nella https://fuss.bz.it/page/info/[pagina informativa].

A differenza del progetto FUSS, l'idea è quella di avere la possibilità scegliere al boot se avviare la distribuzione FUSS oppure Windows.

Nel caso di avvio con Windows, sarebbe possibile usare, nel Laboratorio di Informatica del plesso Benincasa, la rete "192.168.1.x/24" con i precedenti indirizzi per DNS e Gateway, in modo da mantenere la compatibilità piena con la situazione attuale. Il FUSS Server si limita ad inoltrare i pacchetti provenienti e destinati alla rete "192.168.1.x/24".
Se il boot avviene con FUSS Client, allora la rete è la "192.168.2.x/24", il default Gateway e il DNS puntano al FUSS Server e l'accesso alla rete avviene tramite autenticazione al portale Captive usando gli account in Active Directory.

In alternativa a FUSS potrebbe essere valido il software del progetto https://sodilinux.itd.cnr.it/[SoDiLinux] anche se più datato.

.Architettura di rete
[plantuml, "target=architettura-alto-livello", format="svg"]   
....
nwdiag {
  Rete_esterna [shape = cloud desccription="Internet"];
  Rete_esterna -- gateway;
  
  network Altre_ICDL {
      color="#FFCCCC";
      width="full";
      description="Dorsale\nIstituto";
      address="192.168.1.x/24";
      gateway [address="192.168.1.5" shape="node" description="<&cog*3>\nGW"];
      dns [address="192.168.1.3" shape="node" description="<&cog*3>\nDNS"];
      ad [shape="node" description="<&cog*3>\n AD"];
      serverICDL [shape="node" description="<&cog*3>\nICDL"];
      FSB  [address="192.168.1.252"];
      FSS  [address="192.168.1.253"];
      FSF  [address="192.168.1.254"];
    }
    
    group nuovo {
      description="Nodi nuovi";
      color="#00FFFF";
      FSB;
      FSS;
      FSF;
    }
  
    network Lab_Benincasa {
      color="#AAFFAA"
      width="full";
      address="192.168.2.x/24"
      description="LAB INF\nBENINCASA\nLAN+WLAN"

      FSB  [address="192.168.2.254"  shape="node" description="<&cog*3>\n   FUSS\n  Server\nBENINCASA"];
      group B_Cabled {
        description="Rete cablata"
        color="#AAFFAA"
        
        doc_B [address="192.168.2.100/24" description="<&monitor*3>\nINSB"];
        pc_Bx  [address="192.168.2.x/24, 192.168.1.(100+x)/24" description="<&person*3>\nPCBx"];
        
        printer_B1 [address="192.168.2.51/24" description="<&print*3>\n PB1"];
        printer_B2 [address="192.168.2.52/24" description="<&print*3>\n PB2"];
      }
      
      group B_WiFi {
        description="Rete WiFi"
        color="#CCFFCC"
        
        WiFi_By [address="192.168.2.(150 + y)/24" description="<&wifi*3>\n By"];
      }
    }
    
    network Lab_Savoia {
      color="#AAAAFF"
      width="full";
      address="192.168.3.x/24"
      description="LAB INF\nSAVOIA\nLAN+WLAN"
  
      FSS  [address="192.168.3.253" shape="node" description="<&cog*3>\nFUSS\nServer\nSAVOIA"];
      group S_Cabled {
        description="Rete cablata"
        color="#AAAAFF"
        
        doc_S [address="192.168.3.100/24" description="<&monitor*3>\nSINS"];
        pc_Sx  [address="192.168.3.x/24" description="<&person*3>\nPCSx"];
  
        printer_S1 [address="192.168.3.51/24" description="<&print*3>\n PS1"];
        printer_S2 [address="192.168.3.52/24" description="<&print*3>\n PS2"];
      }
      
      group S_WiFi {
        description="Rete WiFi"
        color="#CCCCFF"
        
        WiFi_Sy [address="192.168.3.(150 + y)/24" description="<&wifi*3>\n Sy"];
      }
    }
    network Lab_FL {
      color="#FFAAFF"
      width="full";
      address="192.168.4.x/24"
      description="FutureLAB\nLAN+WLAN"
  
      FSF  [address="192.168.4.254" shape="node" description="<&cog*3>\n   FUSS\n  Server\nFutureLab"];
      group F_Cabled {
        description="Rete cablata"
        color="#FFAAFF"
        
        doc_F [address="192.168.4.100/24" description="<&monitor*3>\nFINS"];
        pc_Fx  [address="192.168.4.x/24" description="<&person*3>\nPCFx"];
  
        printer_F1 [address="192.168.4.51/24" description="<&print*3>\n PF1"];
        printer_F2 [address="192.168.4.52/24" description="<&print*3>\n PF2"];
      }
      
      group F_WiFi {
        description="Rete WiFi"
        color="#FFCCFF"
        
        WiFi_Fy [address="192.168.f.(150 + y)/24" description="<&wifi*3>\n Fy"];
      }
  }
}
....


I https://www.truelite.it/presentazioni/introduzione-architettura-fuss/[servizi] dovrebbero seguire simile al seguente schema.

.Servizi
[plantuml,targer="servizi",format="svg"]
....
title Servizi

cloud Internet {

}

package InfrastrutturaAttuale {
  component [Firewall] as FW1
  component [DNS] as DNS1
  component [LDAP]
  component [NFS]
  component [DHCP] AS DHCP1
  component [Win Domanin File Server] AS WDFS
  DNS1--FW1
  DHCP1 -- DNS1
  WDFS--LDAP
}

 
node "FUSS Server" {
    [HTTP Content Filter] AS HFW
    [HTTP Proxy cache] AS Proxy
    [SSH]
    component [DHCP] AS DHCP2
    [Veyon Master] AS VM
    [HTTP Server] AS Apache
    database "PostgreSQL" {
    }
    database "MySQL" {
    }
    
    interface IVeyon 
    
    Apache -- MySQL
    Apache -- PostgreSQL
    VM --( IVeyon
    
    Proxy -- DNS1
    Proxy -- FW1
} 


package "Windows Clients" {
    component [XMing]
    component [SSH client]
    component [MySQL Client] AS msw
    component [Browser] AS bw
    [Veyon Service] AS VCW
    VCW --( IVeyon
}

package "Linux Clients" {
    [Veyon Service] AS VCL
    VCL --( IVeyon
    [XFree86]
}


FW1 -- Internet
....


=== Transizione

Per gestire il periodo di transizione si deve tenere conto delle seguenti specifiche.

. Il sistema deve permettere la coesistenza con le tecnologie correntemente in uso
. La nuova configurazione non deve interrompere il servizio ICDL
. La rete WiFi è attualmente gestita da MasterCom con politiche di amministrazione ad hoc
. La nuova configurazione non deve interrompere il servizio di stampa
. La nuova configurazione non deve sostituire il firewall ma integrarlo

Nella fase di transizione la rete WiFi all'interno del laboratorio può restare così com'è.

=== Servizi

I FUSS Server hanno un sistema operativo Linux con Gufw come interfaccia al firewall software UFW, inoltre si possono aggiungere regole al DNS.

Il sistema permette l'accesso in `ssh` anche con il server grafico `X`. Il sistema deve configurare come suo default gateway il nodo 192.168.1.5 e come DNS il nodo 192.168.1.3.

La gestione della rete dovrebbe essere già preconfigurata ma nel caso si debbano gestire i precedenti indirizzi di rete si deve abilitare il solo IP forwarding, liberando risorse del kernel.

La RAM dovrebbe essere di almeno 16 GB, il numero di CPU pari ad almeno 8, lo spazio su disco di almeno 256 GB.

I nodi FUSS possono essere PC fisici o macchine virtuali.

Il docente deve possedere un account sui FUSS Server e deve essere nella lista dei `sudoers` (gruppo `sudo`).

Sui computer degli studenti deve essere installato FUSS Client con possibilità di __dual-boot__.
Nel caso di avvio con Windows, deve essere impostato `Veyon` per consentire il monitoraggio.

I servizi offerti dal FUSS Server sono:

* Apache HTTPD Web server
* IP stateful firewall e router 
* HTTP Proxy Cache
* HTTP Proxy Content Filter
* Proxy Secure Shell

Quelli offerti da FUSS Client sono:

* Autenticazione degli utenti tramite server LDAP
* Download e installazione dei certificati SSL necessari
* Mount delle directory HOME tramite NFS
* Installazione chiavi di autenticazione SSH
* Sincronizzazione NSCD
* Inserimento in configurazione cluster
* Creazione di utente locale di amministrazione

https://www.truelite.it/presentazioni/workshop-fuss-server/[L'installazione] ha un wizard.

Si potrebbe usare anche un solo FUSS Server creando due cluster, uno per laboratorio.

=== Pro e contro della soluzione proposta

==== Pro

* Tutte le richieste dei docenti di informatica sono soddisfatte
* Impatto sulla restante rete molto limitato

==== Contro

* Il nuovo nodo rappresenta un punto guasto aggiuntivo
* Se il nuovo nodo diventa indisponibile, la rete del laboratorio non è operativa
* la banda disponibile per PC studente si riduce notevolmente in quanto su un'unica scheda di rete ed un unico host viene gestita, via software, la connessione di tutte le postazioni del laboratorio
* il FUSS sever potrebbe essere congestionato aumentando i tempi di latenza

== Laboratori in mobilità

Una soluzione adottata da molti Istituti è quella di fornire un ambiente di calcolo, detto __classe virtuale__, che esegue il software su un server dell'Istituto ed è accessibile dai PC del laboratorio come da casa.
Di norma sono realizzate tramite tante macchine virtuali installate su un server quante sono le classi omogenee, e possono avere sistemi operativi Windows - con costi di licenza - o Unix-like - senza costi.
Nella macchina virtuale sono installati e configurati dall'assistente tecnico o dal docente  i software per la didattica.

.Uso delle _classi virtuali_
====
* L'utente accede alla propria classe mediante una porta TCP/IP ben specifica.
* Lo studente accede alle macchine virtuali con le stesse credenziali di accesso ai PC (cognome.nome e password come da sistema LDAP).

.Esempio di connessione da scuola:
* MACCHINA VIRTUALE 1ATUR : ip= 10.2.2.13
* MACCHINA VIRTUALE 5FSA: ip=10.2.2.51

.Esempio di connessione da casa:
..MACCHINA VIRTUALE 1ATUR : url= lab.iissavoiabenincasa.it porta TCP:2213
..MACCHINA VIRTUALE 5FSA: url=lab.iissavoiabenincasa.it porta TCP:2251
====

=== Pro e contro

==== Pro

* i computer del laboratorio si comportano come terminali di accesso alle macchine virtuali e necessitano di risorse minimali;
* si semplifica lo svolgimento dei compiti domestici e il loro controllo;
* si permette agli studenti di cambiare postazione nel laboratorio mantenento l'accesso ai loro dati;
* si possono controllare gli accessi di ciascun utente connesso alla macchina virtuale, anche al fine del controllo dei compiti;
////
* possibilità di proiettare lo schermo del docente su ciascun terminale connesso alla macchina virtuale della classe;
* possibilità di favorire l'uso delle macchine virtuali anche a casa, seguendo maggiormente l'andamento didattico di ciascuno studente, specialmente nello svolgimento dei compiti;
////
* si fornisce la possibilità di usare le macchine virtuali anche per l'ausilio alla docenza di altre materie. Se, ad esempio, il docente di Disegno ha bisgno di un CAD, potrebbe creare una macchina virtuale dedicata da condividere con i suoi studenti.

////
Per qeusta soluzione, già implementata in altre scuole, possiamo sentire il tecnico che ha progettato la rete di questa scuola: Matteo Bruschi.
////

==== Contro

* Spreco di risorse interne in quanto i PC del laboratorio sarebbero utilizzati come _thin client_;
* Rinnovo costi di licenza nel caso di software proprietario (Microsoft Windows (R)) sul server;
* Necessità di ingenti risorse di calcolo e di archiviazione sul server.

== Migrazione al Software Libero e art. 68 CAD

Per ridurre, se non azzerare, i costi di licenza del software in uso nei laboratori si potrebbe installare Linux, oppure BSD, come sistema operativo.

Questa opzione è da considerarsi in ottemperanza all'art. 68 del Codice per l'Amministrazione Digitale:

.Art. 68. Analisi comparativa delle soluzioni
[quote,Codice per l'Amministrazione Digitale, Capo VI. SVILUPPO, ACQUISIZIONE E RIUSO DI SISTEMI INFORMATICI NELLE PUBBLICHE AMMINISTRAZIONI]
....
1. Le pubbliche amministrazioni acquisiscono programmi informatici o parti di essi nel rispetto dei principi di economicità e di efficienza, tutela degli investimenti, riuso e neutralità tecnologica, a seguito di una valutazione comparativa di tipo tecnico ed economico tra le seguenti soluzioni disponibili sul mercato:

  a) software sviluppato per conto della pubblica amministrazione;
  b) riutilizzo di software o parti di esso sviluppati per conto della pubblica amministrazione;
  c) software libero o a codice sorgente aperto;
  d) software fruibile in modalità cloud computing;
  e) software di tipo proprietario mediante ricorso a licenza d'uso;
  f) software combinazione delle precedenti soluzioni.

1-bis. A tal fine, le pubbliche amministrazioni prima di procedere all'acquisto, secondo le procedure di cui al codice di cui al decreto legislativo ((n. 50 del 2016)), effettuano una valutazione comparativa delle diverse soluzioni disponibili sulla base dei seguenti criteri:

  a) costo complessivo del programma o soluzione quale costo di acquisto, di implementazione, di mantenimento e supporto;
  b) livello di utilizzo di formati di dati e di interfacce di tipo aperto nonché di standard in grado di assicurare l'interoperabilità e la cooperazione applicativa tra i diversi sistemi informatici della pubblica amministrazione;
  c) garanzie del fornitore in materia di livelli di sicurezza, conformità alla normativa in materia di protezione dei dati personali, livelli di servizio tenuto conto della tipologia di software acquisito.

 1-ter. Ove dalla valutazione comparativa di tipo tecnico ed economico, secondo i criteri di cui al comma 1-bis, risulti motivatamente l'impossibilità di accedere a soluzioni già disponibili all'interno della pubblica amministrazione, o a software liberi o a codici sorgente aperto, adeguati alle esigenze da soddisfare, è consentita l'acquisizione di programmi informatici di tipo proprietario mediante ricorso a licenza d'uso. La valutazione di cui al presente comma è effettuata secondo le modalità e i criteri definiti dall'AgID.
....

Il rimando normativo è alle https://www.agid.gov.it/sites/default/files/repository_files/lg-acquisizione-e-riuso-software-per-pa-docs_pubblicata.pdf[Linee guida su acquisizione e riuso di software per le pubbliche amministrazioni].

Si evidenziano:

comma **1** lettera **c**:: software libero o a codice sorgente aperto
comma **1-bis** lettera **a**:: costo complessivo del programma o soluzione
comma **1-bis** lettera **b**:: [...]utilizzo di formati di dati e di interfacce di tipo aperto[...]

A favore di questa opzione si citano le argomentazioni


* della Free Software Foundation:

** https://www.gnu.org/education/edu-schools.html[Perché la scuola deve usare esclusivamente software libero] di Richard Stallman
* https://www.gnu.org/education/edu-faq.it.html[Domande ricorrenti su software libero ed istruzione]

* di alcuni dei più illustri professori italiani di Informatica:

** https://gliasinirivista.org/scuola-e-universita-perche-preferire-il-software-libero/[Scuola e università: perché preferire il software libero] di https://www.polito.it/personale?p=angelo.meo[Angelo Raffale Meo]
** https://scuolalibera.continuity.space/lettera-professor-meo[Lettera alla ministra Azzolina] di Angelo Raffale Meo
* https://iamarf.org/2022/12/09/libreitalia-conference-2022/[Importanza del Free and Open Source Software (FOSS) per l'istruzione.] di https://iamarf.org/[Andreas Formiconi]
** http://erlug.linux.it/linuxday/2010/contrib/davoli_bo.gld.2010.odp[L'informatica nella Scuola: strumenti e metodi, scienza e tecnologia. La libertà di usare il Software Libero] di https://www.cs.unibo.it/~renzo/[Renzo Davoli]

Gionata Massi per il Dipartimento di Informatica
