= Configurazione dei laboratori di informatica
Gionata Massi <gionata.massi@savoiabenincasa.it>
2022-11-30: Revisione 1
:figure-caption: Figura

== Problematiche dei laboratori

L'attività didattica in laboratorio richiede un'adeguata predisposizione dei PC e dei collegamenti che non sempre si riscontra nelle attuali condizioni.

.Monitoraggio
Una problematica consiste nell'uso, da parte degli studenti, delle tecnologie per fini non didattici che l'insegnante, mentre è impegnato nella presentazione della teoria o nell'illustrazione delle tecniche e dei metodi, non riesce a rilevare. Capita, infatti, che nelle classi numerose gli studenti aprano video-giochi piuttosto che guardino pagine non inerenti l'attività didattica.

.Condivisione di videate
Un'altra problematica è la condivisione delle videate che, sebbene supportata dal proiettore, resta problematica specie per gli studenti delle ultime file.

.Stesse versioni del software
Alle volte il software richiesto per l'attività didattica risulta non disponibile in alcuni PC o installato in versioni diverse e incompatibili.

.Aggiornamento
L'aggiornamento di un software richiede tempo in quanto ogni postazione deve essere aggiornata.

.Controllo _fine_ della rete
Per alcune verifiche è fatto divieto di accedere a risorse esterne al proprio PC oltre a quelle del servizio di erogazione della prova e allo stato attuale il docente non ha controllo sul filtraggio di rete.

.Blocco delle pubblicità 
Per l'accesso ad alcune risorse capita che vi siano pubblicità inserite nelle pagine web e queste causano distrazione oltre a poter presentare contenuti non adatti all'ambito scolastico.

Allo stato attuale le uniche modalità di mitigazione delle problematiche sopra esposte sono l'attenta sorveglianza da parte dell'insegnante e i tempestivi aggiornamenti del software da parte degli assistenti tecnici.

L'attuale scelta dei sistemi inoltre vincola all'utilizzo di ogni dispositivo come stand-alone e solo con un sistema operativo.

Sarebbe auspicabile poter disporre di sistemi operativi aperti, con la possibilità di scegliere il sistema operativo da avviare, software e risorse di calcolo condivise.

.Sistemi a codice sorgente aperto
Per la didattica del linguaggio C++, dei sistemi operativi, delle reti di calcolatori, delle tematiche di cybersicurezza sarebbe opportuno lavorare con Sistemi Operativi liberi quali GNU/Linux o BSD.

.Clustering
Per la sperimentazione di alcuni algoritmi particolarmente onerosi potrebbe richiedere l'utilizzo di più PC come se questi fossero un'unica potente workstation. L'architettura hardware e software deve permettere la creazione di cluster.

.Cloud privato
Per riprendere il controllo dei dati ed evitare le preoccupazioni causate dall'uso di servizi cloud gestiti da fornitori esteri, è da valutare l'introduzione di una piattaforma di condivisione gestita internamente.

== Requisiti dell'ambiente laboratoriale di Informatica

Per facilitare l'insegnamento in ambienti di apprendimento digitale devono essere soddisfatte le seguenti specifiche:

. Il docente deve poter gestire i PC del laboratorio
.. Il docente deve poter monitorare a distanza i PC del laboratorio
... Il docente deve poter visualizzare la schermata dei PC del laboratorio dove sta insegnando
... Il docente deve poter salvare la schermata dei PC del laboratorio dove sta insegnando
.. Il docente deve poter controllare a distanza i PC del laboratorio
... Il docente deve poter bloccare i dispositivi di input
... Il docente deve poter prelevare da remoto i file
... Il docente deve poter trasmettere lo schermo del proprio PC a quello degli studenti
.. Il docente e studenti devono poter condividere gli schermi
. Il docente deve poter condividere applicazioni e servizi con gli studenti
.. Il docente deve poter gestire una macchina Linux, reale o virtuale, per creare e rimuovere utenti, applicazioni e servizi
.. La macchina linux si collega al servizio LDAP oppure mantiene l'elenco degli utenti
.. Il docente deve poter installare pacchetti sulla macchina Linux
.. Il docente deve poter avviare e terminare servizi sulla macchina Linux
.. I PC devono poter avviare le applicazioni sulla macchina Linux
... I PC devono supportare lo X11 forwarding per le applicazioni grafiche
. Il docente deve poter controllare gli accessi ad internet
.. Il docente deve poter impedire l'accesso ai file sul Drive e nelle cartelle condivise, ad eccezione dell'eventuale deposito della prova;
.. Il docente deve poter impedire la ricerca di informazioni nella rete Internet su siti non esplicitamente consentiti (whitelist)
.. Il docente deve poter impedire lo scambio di messaggi con sistemi di chat (es: Google Chat), webmail (es: GMail) o altro (es: Whatsapp web, Google Drive).
. Il docente deve poter controllare il DNS per rimuovere messaggi pubblicitari

== Applicazioni

. Monitoraggio e controllo
.. https://veyon.io/it/[Veyon]
. Applicazioni
.. Software per l'ufficio
... https://it.libreoffice.org/[LibreOffice]
.... Base
.... Calc
.... Charts
.... Draw
.... Impress
.... Math
.... Writer
.. Software per l'editoria
... https://www.tug.org/texlive/[TeX Live]
... https://asciidoctor.org/[Asciidoctor]
.... https://docs.asciidoctor.org/diagram-extension/latest/[Asciidoctor Diagram]
.... https://docs.asciidoctor.org/pdf-converter/latest/[Asciidoctor PDF]
.... https://docs.asciidoctor.org/epub3-converter/latest/[Asciidoctor EPUB3]
.... https://docs.asciidoctor.org/reveal.js-converter/latest/[Asciidoctor reveal.js]
.... rouge
.... coderay
.... pygments.rb
.. Interpreti, compilatori, debugger, toolchain
... https://gcc.gnu.org/[GCC, the GNU Compiler Collection]
... https://clang.llvm.org/[Clang]
... https://www.php.net/[php]
... https://nodejs.org/[Node.js] + https://pnpm.io/it/[pnpm] + https://www.typescriptlang.org/[TypeScript] + https://nativescript.org/[NativeScript]
... https://www.python.org/[Python 3]
... https://www.r-project.org/[R]
... https://www.ruby-lang.org/it/[Ruby]
... https://www.minizinc.org/[MiniZinc]
... https://www.sourceware.org/gdb/[gdb]
... https://lldb.llvm.org/[lldb]
... https://valgrind.org/[Valgrind]
... https://ghidra-sre.org/[ghidra]
... https://cmake.org/[CMake]
... https://www.gnu.org/software/make/[GNU Make]
.. Ambienti integrati di sviluppo
... https://code.visualstudio.com/[VS Code]
//... QT Creator
... https://www.codeblocks.org/[Code::Blocks IDE]
... https://www.vim.org/[vim]
... https://jupyter.org/[Jupyter Lab]
...  https://posit.co/products/open-source/rstudio/[RStudio Desktop Open Source Edition]
... http://www.flowgorithm.org/[Flowgorithm], https://www.imparando.net/sito/strumenti_di_sviluppo/flowgorithm/come_installare_in_linux.htm[sotto Linux]
.. Strumenti di versionamento
... git
.. Accesso remoto
... ssh
... netcat
... openVPN client
.. Audio e video
... Audacity
... FFMPEG
... Shotcut
.. Browser
... Firefox
... Chrome
.. CAD
... FreeCad
.. Grafica
... GNU Image Manipulation Program
... Inkscape
... GraphViz
... GnuPlot
... imagemagick
... PlantUML
... Kroki
.. Calcolo scientifico e ingegneristico
... GNU Octave (octave-forge)
... Scilab
... GeoGebra
... R
... miniconda
.. MindMapping
... FreePlane
.. Software per l'analisi della rete
... WireShark
... ping
.. Software per la configurazione del firewall
... gufw
. Servizi
.. Web server
... Apache
... Nginx
.. Data base
... PostgreSQL
... MySQL
.. Consegna dei compiti di programmazione
... CMS
... CMSSocial
.. DBMS
... PostgresSQL
... MySQL
.. Cloud
... Nextcloud
.. Privacy
... GNU GPG
... https://apps.kde.org/it/kleopatra[Kleopatra]

== Architettura ipotizzata

L'archittura di riferimento è quella del progetto https://it.wikipedia.org/wiki/FUSS[FUSS], meglio dettagliato nella https://fuss.bz.it/page/info/[pagina informativa].

A differenza del progetto FUSS, l'idea è quella di avere la possibilità scegliere al boot se avviare la distribuzione FUSS oppure Windows.

Nel caso di avvio con Windows, sarebbe possibile usare, nel Laboratorio di Informatica del plesso Benincasa, la rete "192.168.1.x/24" con i precedenti indirizzi per DNS e Gateway, in modo da mantenere la compatibilità piena con la situazione attuale. Il FUSS Server si limita ad inoltrare i pacchetti provenienti e destinati alla rete "192.168.1.x/24".
Se il boot avviene con FUSS Client, allora la rete è la "192.168.2.x/24", il default Gateway e il DNS puntano al FUSS Server e l'accesso alla rete avviene tramite autenticazione al portale Captive usando gli account in Active Directory.

.Architettura di rete
[plantuml, "target=architettura-alto-livello", format="svg"]   
....
nwdiag {
  Rete_esterna [shape = cloud desccription="Internet"];
  Rete_esterna -- gateway;
  
  network Altre_ICDL {
      color="#FFCCCC";
      width="full";
      description="Dorsale\nIstituto";
      address="192.168.1.x/24";
      gateway [address="192.168.1.5" shape="node" description="<&cog*3>\nGW"];
      dns [address="192.168.1.3" shape="node" description="<&cog*3>\nDNS"];
      ad [shape="node" description="<&cog*3>\n AD"];
      serverICDL [shape="node" description="<&cog*3>\nICDL"];
      FSB  [address="192.168.1.252"];
      FSS  [address="192.168.1.253"];
  

    }
    
    group nuovo {
      description="Nodi nuovi";
      color="#00FFFF";
      FSB;
      FSS;
    }
  
    network Lab_Benincasa {
      color="#AAFFAA"
      width="full";
      address="192.168.2.x/24"
      description="LAB INF\nBENINCASA\nLAN+WLAN"

      FSB  [address="192.168.2.254"  shape="node" description="<&cog*3>\n   FUSS\n  Server\nBENINCASA"];
      group B_Cabled {
        description="Rete cablata"
        color="#AAFFAA"
        
        doc_B [address="192.168.2.100/24" description="<&monitor*3>\nINSB"];
        pc_Bx  [address="192.168.2.x/24, 192.168.1.(100+x)/24" description="<&person*3>\nPCBx"];
        
        printer_B1 [address="192.168.2.51/24" description="<&print*3>\n PB1"];
        printer_B2 [address="192.168.2.52/24" description="<&print*3>\n PB2"];
      }
      
      group B_WiFi {
        description="Rete WiFi"
        color="#CCFFCC"
        
        WiFi_By [address="192.168.2.(150 + y)/24" description="<&wifi*3>\n By"];
      }
    }
    
    network Lab_Savoia {
      color="#AAAAFF"
      width="full";
      address="192.168.3.x/24"
      description="LAB INF\nSAVOIA\nLAN+WLAN"
  
      FSS  [address="192.168.3.253" shape="node" description="<&cog*3>\nFUSS\nServer\nSAVOIA"];
      group S_Cabled {
        description="Rete cablata"
        color="#AAAAFF"
        
        doc_S [address="192.168.3.100/24" description="<&monitor*3>\nSINS"];
        pc_Sx  [address="192.168.3.x/24" description="<&person*3>\nPCSx"];
  
        printer_S1 [address="192.168.3.51/24" description="<&print*3>\n PS1"];
        printer_S2 [address="192.168.3.52/24" description="<&print*3>\n PS2"];
      }
      
      group S_WiFi {
        description="Rete WiFi"
        color="#CCCCFF"
        
        WiFi_Sy [address="192.168.3.(150 + y)/24" description="<&wifi*3>\nSy"];
      }
    }
  }
}
....


I https://www.truelite.it/presentazioni/introduzione-architettura-fuss/[servizi] dovrebbero seguire lo schema seguente.

.Servizi
[plantuml,targer="servizi",format="svg"]
....
title Servizi

cloud Internet {

}

package InfrastrutturaAttuale {
  component [Firewall] as FW1
  component [DNS] as DNS1
  component [LDAP]
  component [NFS]
  component [DHCP] AS DHCP1
  component [Win Domanin File Server] AS WDFS
  DNS1--FW1
  DHCP1 -- DNS1
  WDFS--LDAP
}

 
node "FUSS Server" {
    [HTTP Content Filter] AS HFW
    [HTTP Proxy cache] AS Proxy
    [SSH]
    component [DHCP] AS DHCP2
    [Veyon Master] AS VM
    [HTTP Server] AS Apache
    database "PostgreSQL" {
    }
    database "MySQL" {
    }
    
    interface IVeyon 
    
    Apache -- MySQL
    Apache -- PostgreSQL
    VM --( IVeyon
    
    Proxy -- DNS1
    Proxy -- FW1
} 


package "Windows Clients" {
    component [XMing]
    component [SSH client]
    component [MySQL Client] AS msw
    component [Browser] AS bw
    [Veyon Service] AS VCW
    VCW --( IVeyon
}

package "Linux Clients" {
    [Veyon Service] AS VCL
    VCL --( IVeyon
    [XFree86]
}


FW1 -- Internet
....


=== Transizione

Per gestire il periodo di transizione si deve tenere conto delle seguenti specifiche.

. Il sistema deve permettere la coesistenza con le tecnologie correntemente in uso
. La nuova configurazione non deve interrompere il servizio ICDL
. La rete WiFi è attualmente gestita da MasterCom con politiche di amministrazione ad hoc
. La nuova configurazione non deve interrompere il servizio di stampa
. La nuova configurazione non deve sostituire il firewall ma integrarlo

Nella fase di transizione la rete WiFi all'interno del laboratorio può restare così com'è.

=== Servizi

I FUSS Server hanno un sistema operativo Linux con Gufw come interfaccia al firewall software UFW, inoltre si possono aggiungere regole al DNS.

Il sistema permette l'accesso in `ssh` anche con il server grafico `X`. Il sistema deve configurare come suo default gateway il nodo 192.168.1.5 e come DNS il nodo 192.168.1.3.

La gestione della rete dovrebbe essere già preconfigurata ma nel caso si debbano gestire i precedenti indirizzi di rete si deve abilitare il solo IP forwarding, liberando risorse del kernel.

La RAM dovrebbe essere di almeno 16 GB, il numero di CPU pari ad almeno 8, lo spazio su disco di almeno 256 GB.

I nodi FUSS possono essere PC fisici o macchine virtuali.

Il docente deve possedere un account sui FUSS Server e deve essere nella lista dei `sudoers` (gruppo `sudo`).

Sui computer degli studenti deve essere installato FUSS Client con possibilità di __dual-boot__.
Nel caso di avvio con Windows, deve essere impostato `Veyon` per consentire il monitoraggio.

I servizi offerti dal FUSS Server sono:

* Apache HTTPD Web server
* IP stateful firewall e router 
* HTTP Proxy Cache
* HTTP Proxy Content Filter
* Proxy Secure Shell

Quelli offerti da FUSS Client sono:

* Autenticazione degli utenti tramite server LDAP
* Download e installazione dei certificati SSL necessari
* Mount delle directory HOME tramite NFS
* Installazione chiavi di autenticazione SSH
* Sincronizzazione NSCD
* Inserimento in configurazione cluster
* Creazione di utente locale di amministrazione

https://www.truelite.it/presentazioni/workshop-fuss-server/[L'installazione] ha un wizard.

Si potrebbe usare anche un solo FUSS Server creando due cluster, uno per laboratorio.

=== Pro e contro della soluzione proposta

==== Pro

* Tutte le richieste dei docenti di informatica sono soddisfatte
* Impatto sulla restante rete molto limitato

==== Contro

* Il nuovo nodo rappresenta un punto guasto aggiuntivo
* Se il nuovo nodo diventa indisponibile, la rete del laboratorio non è operativa
* la banda disponibile per PC studente si riduce notevolmente in quanto su un'unica scheda di rete ed un unico host viene gestita, via software, la connessione di tutte le postazioni del laboratorio
* il FUSS sever potrebbe essere congestionato aumentando i tempi di latenza

Gionata Massi